
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_google_ads_transform'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  google_adgroup_perf_source: "INCUBATION.DBT_GOOGLE_ADS.ADGROUP_PERFORMANCE_REPORT"
  google_ad_perf_source: "INCUBATION.DBT_GOOGLE_ADS.AD_PERFORMANCE_REPORT"
  google_click_perf_source: "INCUBATION.DBT_GOOGLE_ADS.CLICK_PERFORMANCE_REPORT"
  bing_adgroup_perf_source:   "INCUBATION.DBT_BING_ADS.AD_GROUP_PERFORMANCE_REPORT"
  sfdc_lead_source:        "INCUBATION.DBT_SFDC.LEAD"
  sfdc_account_source:     "INCUBATION.DBT_SFDC.ACCOUNT"
  sfdc_contact_source:     "INCUBATION.DBT_SFDC.CONTACT"
  sfdc_opportunity_source: "INCUBATION.DBT_SFDC.OPPORTUNITY"
  exchange_rates_source:   "INCUBATION.DBT_SFDC.CURRENCYTYPE"
  start_date: '2018-01-01' # optional, default to '2018-01-01' if not present
  use_hashed_email: false   # optional, default to 'false' if not present


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
#vars:
#  etl:                            stitch #stitch or fivetran
#  criteria_performance_report:    "dbt_google_ads.criteria_performance_report" #"schema.table"
#  click_performance_report:       "dbt_google_ads.click_performance_report" #"schema.table"
#  final_url_performance_report:   "dbt_google_ads.final_url_report" #"schema.table"
#  ads_table:                      "dbt_google_ads.ads" #"schema.table" (only for stitch)
#  ad_groups_table:                "dbt_google_ads.ad_group" #"schema.table" (only for stitch)
#  accounts_table:                 "dbt_google_ads.accounts" #"schema.table" (only for stitch)
#  campaigns_table:                "dbt_google_ads.campaigns" #"schema.table" (only for stitch)
#  adapter_value:                  criteria #url or criteria

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_google_ads_transform:
      paid_ads:
          materialized: view
      sfdc:
          materialized: view
      analytical:
          materialized: view

