
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_google_ads_transform'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  database_name:           "INCUBATION"         # Database name
  source_schema_ads:       "DBT_GOOGLE_ADS"     # Source schema of the Paid Ads
  source_schema_sfdc:      "DBT_SFDC"           # Source Schema of Salesforce
  start_date:              '2018-01-01'         # Start date to filter the Ads/Salesforce data
  use_hashed_email:        false                # Hash the email in result tables/views


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
#vars:
#  etl:                            stitch #stitch or fivetran
#  criteria_performance_report:    "dbt_google_ads.criteria_performance_report" #"schema.table"
#  click_performance_report:       "dbt_google_ads.click_performance_report" #"schema.table"
#  final_url_performance_report:   "dbt_google_ads.final_url_report" #"schema.table"
#  ads_table:                      "dbt_google_ads.ads" #"schema.table" (only for stitch)
#  ad_groups_table:                "dbt_google_ads.ad_group" #"schema.table" (only for stitch)
#  accounts_table:                 "dbt_google_ads.accounts" #"schema.table" (only for stitch)
#  campaigns_table:                "dbt_google_ads.campaigns" #"schema.table" (only for stitch)
#  adapter_value:                  criteria #url or criteria

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_google_ads_transform:
      paid_ads:
          materialized: view
      sfdc:
          materialized: view
      analytical:
          materialized: view

